version: "2.2"
services:
  app:
    container_name: koa-boilerplate
    restart: always
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      NODE_ENV: docker
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/Users/shenyiling/mongodb/data/db:/data/db"